title: EngineerLK
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog for mechanical and mechatronics engineers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed
  - jekyll-archives

jekyll-archives:
  enabled:
    - tags
    - categories
    - authors
  layouts:
    tag: archive
    category: archive
    author: archive
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
    author: /authors/:name/
